const fs = require('fs')
const chalk = require('chalk')

//Api Website\\
global.APIs = {
	zenz: 'https://zenzapis.xyz',
}

//Api Key\\
global.APIKeys = {
	'https://zenzapis.xyz': 'your key',
}

global.alivemsg = `📤I am alive now😇
🤷‍♀️How can I help you?😉` //Costomize Alive Message (type your message in `` )


global.autoTyping = false //auto tying in gc (true to on, false to off)
global.autoreadpmngc = false //auto reading in gc and pm (true to on, false to off)
global.autoReadGc = false //auto reading in gc (true to on, false to off)
global.autoRecord = false //auto recording (true to on, false to off)
global.available = true //auto available (true to on, false to off)

global.doc1 = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
global.doc2 = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
global.doc3 = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
global.doc4 = 'application/zip'
global.doc5 = 'application/pdf'
global.doc6 = 'application/vnd.android.package-archive'

//owner v card
global.vcardowner = ['+263787417466'] // owner number
global.ownername = "keen-kedira" // owner name
global.ytname = "" // yt chanel name
global.socialm = "GitHub: keen-kefira" // github or insta name
global.location = "Africa, Zimbabwe, Harare" // location

//bot body 
global.alivepic = `https://i.ibb.co/wy5PbRf/IMG-20220805-WA0003.jpg` // alive picture \\ use "https://ibb.com" to upload photos. < 1 MB

global.dragonchat = "false"  // chat bot  "true" / "false" (200 auto replies in this)
global.callblock = "false" // call block "true" / "false" ("true"  to block callers)
global.antibad = "false" // To remove bad word senders
global.antilink = "false" // To remove group link sharing peoples
global.upsongvoice = "true" // bot can upload song as voice note (it use your data and storage bacause auto download) you can put "false" (anyone can't get songs as voice note / your data is not wasted)

global.owner = ['+263787417466']
global.ownertag = '+263787417466' //your tag number
global.botname = '--K-T-G-- - 𝘉𝘖𝘛' //ur bot name
global.packname = "Bot ktg Sticker" // sticker packname
global.author = "--K-T-G--" // sticker author
global.dragonemoji = '🧩' // Menu emoji
global.footer = '[ ◉ - - K-T-G--]' //

global.button = '☰ WHATSAPP OWNER ☰' //Costomize A Button Name In Alive Message
global.btnurl = 'https://wa.me/+263787417466' //Change Your Button's URL

//database
global.premium = ['+263787417466'] //ur premium numbers

//other
global.sessionName = 'session'
global.antitags = false
global.prefa = ['','!','.','😂','❤️','💠'] //Command Prefix eg:(.alive ,alive 😂alive)
global.sp = '💠'
global.mess = {
    success: 'Done ✅',
    admin: 'Only Admins can use it!😉',
    botAdmin: 'Bot wants to be an Admin😥',
    owner: 'Only Owner can use this!😉',
    group: 'Feature Used Only For Groups!',
    private: 'This Features Only For Private Chat!',
    bot: 'This Feature Is Only For Bot😝',
    wait: '👉👈Pleas Wait...',
    error: 'Error!!! Maybe Api Key Is Expired🤔!',
    endLimit: 'Your Daily Limit Has Expired, The Limit Will Be Reset Every 12 Hours',
    linkm: 'Where is the link?',
    nsfw: 'The nsfw feature has not been activated, please contact the admin to activate',
    banChat: 'The bot was banned in this group, please contact the owner to unban',
    badwords: '*🚫Bad Words Not Allowed Here !*\n\n⚠️ Warning... ⚠️',
    caption: 'Generated by: ◉ *--K-T-G--*'
} // END \\
    global.limitawal = {
    premium: "Infinity",
    free: 12,
    monayawal: 1000
}
   global.rpg = {
   darahawal: 100,
   besiawal: 15,
   goldawal: 10,
   emeraldawal: 5,
   umpanawal: 5,
   potionawal: 1
}
global.thum = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur thumb pic
global.log0 = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur logo pic
global.err4r = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur error pic
global.thumb = fs.readFileSync("./Android/AllData/theme/repl.jpg") //ur thumb pic

global.thumb = fs.readFileSync('./Android/AllData/theme/repl.jpg')
global.flaming = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=sketch-name&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.fluming = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=fluffy-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.flarun = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=runner-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='
global.flasmurf = 'https://www6.flamingtext.com/net-fu/proxy_form.cgi?&imageoutput=true&script=smurfs-logo&doScale=true&scaleWidth=800&scaleHeight=500&fontsize=100&text='

global.ntilinkytvid = []
global.ntilinkytch = []
global.ntilinkig = []
global.ntilinkfb = []
global.ntilinktg = []
global.ntilinktt = []
global.ntilinktwt = []
global.ntilinkall = []
global.nticall = []
global.ntwame = []
global.nttoxic = []
global.ntnsfw = []
global.ntvirtex = []
global.rkyt = []
global.wlcm = []
global.gcrevoke = []
global.autorep = []
global.ntilink = []





































// DO NOT CHANGE THIS. ERROR WARNING දාන්න තැනක් නැතුව මෙතන දැම්මෙ.
global.rep = { // All Replies = 145
    K1: '🫢හායි😁❤️',
    K2: '🤭හූයි✌️💞🫶',
    K3: '😉🫶හායි😂',
    K4: '🥴හූයි😊',
    K5: '😂හේයි, හව් ආ යූ🥴✌️',
    K6: '😁Hey there💝 I am WhatsApp Bot😏',
    K7: '❣️ඇයි හලෝ😌',
    K8: '🙃මොකෝ හලෝ🥲',
    K9: '😒මොකෝ?',
    K10: '🥺ඇයි අනේ?❤️🫢',
    K11: '🌝❤️',
    K12: '😜හී හී😁හූ හූ',
    K13: '😁හී හී💞',
    K14: '😊හූ...',
    K15: 'ඇයි🥲',
    K16: '😂😂✌️',
    K17: '😐ආහ්',
    K18: 'චූටී තමයි😇',
    K19: '🥺🥺ඇයි සුදූ❤️💓',
    K20: 'කොහොමවත් නෑ ඉතිං😒',
    K21: '😁මන් දන්නෑ🥲',
    K22: 'හොඳයි තමා😌',
    K23: '😂😂මරු හැබැයි',
    K24: 'මලු🙃',
    K25: '😘😇❤️',
    K26: '😘😘මෙන්න ඔයාට💕',
    K27: '😊ඇත්තමද?❤️',
    K28: '☺️👻ඔය ඇත්තමද❤️',
    K29: 'ඇයි🙄',
    K30: '🥺✌️සිදෙනවද?',
    K31: '😐💔ඕවට එන්න එපා හරිත😒',
    K32: '😏අනේ මේ😒 යනෝ යන්න💔',
    K33: 'ඔයා තමයි හොරා😒 මගෙ හිත හොරකම් කළානෙ ඉතිං😌',
    K34: '😇මොකො හූම් ගාන්නෙ😒 බකමූනා',
    K35: '​😁😁මොකෝ හලෝ හූම් හූම් ගාන්නෙ?',
    K36: '😉නෑ අනේ මුකුත් නෑ😐🫠',
    K37: '😒ආහ්',
    K38: '✌️ඔව් නං එච්චරයි😌',
    K39: '😐හේ හේ නැද්ද?🫣',
    K40: '🙄මොනවටද ආස?',
    K41: '😌මාත් ආසයි😊💞',
    K42: 'එල😌',
    K43: 'බැරි නං නිකං ඉන්න😏',
    K44: '😂😂💔',
    K45: 'සුදුයි තමයි ඇයි මොකද?🙄',
    K46: '😇තාම කෑවෙ නෑ අනේ🥺',
    K47: 'බොන්නෑ😒',
    K48: 'නිදිමත නං දිදාගන්නකො වද දෙන්නැතුව😒😌❤️',
    K49: '😇දැම්ම නිදාගන්න බෑ අනේ😜 නිදිමත නෑ😁💞',
    K50: '😉මුකුත් නෑ අනේ🫡',
    K51: 'මොකද්ද දන්නෑ🥲',
    K52: '😝මම නං මුකුත් කරන්නෑ අනේ😁 ඔයාලා දිහා බලන් ඉන්නවා😌',
    K53: '🥺පාලුයි අනේ. අපි සෙල්ලමක් කරමුද?😊✌️',
    K54: '😌😁ආදරෙයි❤️',
    K55: '😌ආදලෙයි ඉතිං❤️❤️',
    K56: '🥺🥺ඇත්තද?',
    K57: '
